version: '3'
services:
#  ubuntu:
#   container_name : ubuntu
#   # image : ubuntu:23.10
#   build: ./ubuntu
#   volumes:
#     - ../public:/var/www/html
#   command:
#     bash /root/init.sh

  php:
    container_name : php
    build : ./php
    volumes:
      # - ./php/php.ini:/etc/php81/php.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ../public:/var/www/html
    working_dir: /var/www/html


  nginx:
    container_name: nginx
    build : ./nginx
    ports:
      - 8088:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../public:/var/www/html
    depends_on:
      - php
